### PR TITLE
Added myself to player list

### PR DESCRIPTION
**Pull request by thoughtpalette**
@kingtomato Let me know if there needs to be any more changes. Thanks! :cake:

### CODE REVIEW

**Comment by bchristie** [comment]
I'm sorry dude, just saw the pull request (but already added it). ;p Next time you gotta get up in my face! ;-)

**Comment by thoughtpalette** [comment]
lol it's all good :} 

Thanks! :+1:

**Comment by bchristie** [comment]
Feel free to sync changes to your branch, then (as you see other names) submit pull requests on them. Just be sure to @mention this name as well. I don't check the kt email very frequently these days, but this account goes straight to phone.

**Comment by thoughtpalette** [comment]
Sounds great! I'll hit that up.

**Pull request closed without merging**
